### PR TITLE
Allow GCC 10+ compilation

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

In #16, I updated the AD code and ADFirstAidKit to use Tapenade 3.16 instead of 3.10. However, the newer ADFirstAidKit is not compatible with GCC 10+ because of type mismatches. ~~I reverted the ADFirstAidKit files to Tapenade 3.10 in this PR. The actual AD code is still generated with Tapenade 3.16.~~

I added `-fallow-argument-mismatch` to the  F77 gfortran flags to allow compilation with GCC 10+.

## Expected time until merged

2-3 days

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by eirikurj** [comment]
I would prefer to keep the 3.16 files to be consistent to the version used. The alternative would be to apply the `-fallow-argument-mismatch` or develop an explicit interface for these functions. Overall, I think any approach would be a temporary fix anyway, since I know that the Tapenade team is moving away from including an `adbuffer.f` file, and it will be removed or deprecated in future versions. What do you think?

**Comment by sseraj** [comment]
> The alternative would be to apply the `-fallow-argument-mismatch`

Now that you mention it, I think adding `-fallow-argument-mismatch` to just the F77 flags is the cleanest approach

**Comment by eirikurj** [comment]
Since this flag is not available for GCC < 10, I think you need something similar to what was done in https://github.com/mdolab/adflow/pull/244, then all versions should work.

**Comment by sseraj** [comment]
> Since this flag is not available for GCC < 10, I think you need something similar to what was done in [mdolab/adflow#244](https://github.com/mdolab/adflow/pull/244), then all versions should work.

You're right. I just pushed an update.

**Review by eirikurj — APPROVED** [review]

**Review by yqliaohk — APPROVED** [review]

**Pull request merged**
