### PR TITLE
Fixed CGNS deallocation

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

The new Intel compilers we are testing in mdolab/docker#266 revealed bugs in the CGNS API deallocation routine. I fixed the bugs by adding more deallocation safeguards and assigning the correct value for `nZones`. I also removed the `nullify` calls for some attributes because they are not needed and only work with `pointer` types, not `allocatable`.

## Expected time until merged

2-3 days

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

I pulled the `u22-intel-impi-latest-amd64-failed` image from the Docker PR and tested that the tests pass with this fix.

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [x] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by A-CGray — APPROVED** [review]
Nice, just tested this out on the u22-intel-latest image from https://github.com/mdolab/docker/pull/266 and all tests passed.

Is this a bug in CGNS that we should tell them about?

**Comment by sseraj** [comment]
It's not a bug in the CGNS library but in how pySurf reads and stores the CGNS mesh, so no need to open a bug report

**Comment by eirikurj** [comment]
@sseraj overall looks good. However, there are other instances of pointers floating around, but I doubt that there is a need for that. Am I missing something?

**Comment by sseraj** [comment]
@eirikurj Could you clarify your comment?

**Comment by sseraj** [comment]
@eirikurj I changed the remaining pointers in CGNSInterface to allocatables and commented out the unused variables

**Review by A-CGray — APPROVED** [review]

**Review by eirikurj — APPROVED** [review]

**Pull request merged**
